version: '3'
services:
  library_app:
    depends_on:
      - mongo
    restart: always
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
    ports:
      - '27017:27017'
